version: 2

config_android: &config_android
  docker:
    - image: circleci/android:api-28-alpha
  environment:
    JAVA_TOOL_OPTIONS: "-Xmx1024m"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    TERM: dumb

jobs:
  build:
    <<: *config_android
    steps:
      - checkout
      - run:
          name: Build
          command: |
            ./gradlew build --stacktrace